server:
   port: 9753
spring:
   application:
      name: comsumer3
   cloud:
      stream:
         bindings:
            input: #通道名称,使用stream默认的通道名称,可以自定义
               destination: stream-demo-trans #要写入的消息队列的名称
               group: comsumerGroup2 #该属性确保服务只处理一次
         kafka: #使用kafka作为服务中的消息总线
            binder:
               zkNodes: localhost:2181 #zookeeper的网络位置,如果是集群,逗号分割
               brokers: localhost:9092 #kafka的网络位置    
               auto-create-topics: true