server:
   port: 8750
spring:
   application:
      name: producer
   profiles:
      active:
         concurrency
   cloud:
      stream:
         bindings:
            output: #通道名称,使用stream默认的通道名称,可以自定义
               destination: stream-demo #要写入的消息队列的名称
               content-type: application/json #发送或接受什么类型的消息
            example-topic-input:
               destination: test-topic
               group: test-topic-group
               consumer:
                  max-attempts: 1
            example-topic-output:
               destination: test-topic
               consumer:
                  max-attempts: 1
         kafka: #使用kafka作为服务中的消息总线
            binder:
               zk-nodes: localhost:2181 #zookeeper的网络位置,如果是集群,逗号分割
               brokers: localhost:9092 #kafka的网络位置   
               auto-create-topics: true